### ISSUE TITLE
Missing files 

### ISSUE THREAD

**Issue by helloworld0000red** [xo1337/cpp-rust-internal#2]
There apears to be no modules/offsets.hpp to replace and no il2cpp.h i also have no idea what offsets i need to replace since i get from config.json: 

{
  "DumpMethod": true,
  "DumpField": true,
  "DumpProperty": true,
  "DumpAttribute": true,
  "DumpFieldOffset": true,
  "DumpMethodOffset": true,
  "DumpTypeDefIndex": true,
  "GenerateDummyDll": true,
  "GenerateStruct": true,
  "DummyDllAddToken": true,
  "RequireAnyKey": true,
  "ForceIl2CppVersion": false,
  "ForceVersion": 16,
  "ForceDump": false,
  "NoRedirectedPointer": false
}

**Comment by xo1337** [comment]
Sorry about that, the rest of the missing files for the project have been uploaded. In offsets.hpp is all the offsets it says you need.

**Comment by helloworld0000red** [comment]
Hey thanks I saw now very W will compile

**Comment by helloworld0000red** [comment]
> Sorry about that, the rest of the missing files for the project have been uploaded. In offsets.hpp is all the offsets it says you need.

hey can i just find out where i can find UnityEngine.Transform.get_position_Injected
